### ISSUE TITLE
Statikus analízis eszköz futtatása és jelzett hibák átnézése + külön wikilap a feladat dokumentálására

### ISSUE THREAD

**Issue by noramurakozy** [BME-MIT-IET/IETeam-iet-2019#2]

**Comment by toosyz** [comment]
### **Kód analízis SonarQube-bal**:
 Sikertelen, az Analysis örökké pending állapotban marad.

### **Kód analízis Codacy-val**:

Talált hibák típusa és száma
- Security, 42
- Error Prone, 181
- Code Style, 2
- Compatibility, 0
- Unused Code, 11
- Performance, 0
Össz.: 236

A kapott hibák természetüknél fogva nem mindig eltávolítandók, például: kommentelt kód, ami alternatívaként szolgálhat egy másik kódsornak; függvényparaméterek, amiket ugyan egy adott függvény nem használ, egy ugyanolyan nevű másik függvény igen, satöbbi. Az "unused code" kategóriából tehát nem kellett átjavítani dolgokat.

A "security" kategóriában gyakran tűnt fel a **hiányzó default ágak a switch case-eknél**, ezeket átjavítottam. Ezután a security kategóriában egyetlen helyen kívül már csak sárga (ergó kevésbé fontos) hibák maradtak. 

Az if és foreach ágaknál kapcsos zárójeleket adtam hozzá.

Eddigi javítások után:
Security, 35
Error Prone, 162
Code Style, 2
Compatibility, 0
Unused Code, 8
Performance, 0
Össz: 207

**Eddigi munkához tartozó commit-ok:**
Codacy #1: security
Codacy #2: security 2
Codacy #3 error prone if branches updated with curly braces
Codacy #4 some more error cleanup

**Comment by toosyz** [comment]
### Kód javítás 2:

Újabb javítások után a hibák:
Security, 4
Error Prone, 155
Code Style, 2
Compatibility, 0
Unused Code, 8
Performance, 0
Össz.: 169

A javításokkor a System.Exception dobásokat specifikus kivételekre cseréltem ki, a maradék kapcsoszárójeleket beleírtam, és egy erősebb, asszimetrikus hash-t raktam be az eredeti helyett.

**A munkához tartozó commit-ok:**
<a href="https://github.com/BME-MIT-IET/IETeam-iet-2019/commit/a5ab9ed2c677fb2b8a3df2c3d8ff87443d797386">Codacy #5 correction of exceptions</a>
<a href="https://github.com/BME-MIT-IET/IETeam-iet-2019/commit/59c38924a8852bbe54032cf54a85e37cd2a95b10">Codacy #6 final error corrections</a>
<a href="https://github.com/BME-MIT-IET/IETeam-iet-2019/commit/77f39f4b68518eb8293aaa77414ebfc819bda3ac">Codacy #7 different hash</a>
<a href="https://github.com/BME-MIT-IET/IETeam-iet-2019/commit/afc436c689ee3c0c182e937c5055e132e6ec4d87">Reverse change that resulted in build failure</a>

**Comment by toosyz** [comment]
### Kód javítás 2 kiegészítés:

Az előző kommenthez még: ki lettek javítva azok az alapértékes függvényváltozók, helyettük több, ugyanolyan nevű függvényt raktam be (override).

**Comment by toosyz** [comment]
### Kód javítás 3:

Eltávolítottam a kikommentelt kódsorokat.

Javítások utáni hibák:
Security, 4
Error Prone, 155
Code Style, 2
Compatibility, 0
Unused Code, 6
Performance, 0
Össz.: 167

A munkához tartozó commit-ok:
<a href="https://github.com/BME-MIT-IET/IETeam-iet-2019/commit/7e3a7412b17675e77a35d2da396054c995480e78">Codacy #8 removing commented out code</a>

**Comment by noramurakozy** [comment]
A javításokat ellenőriztem, mindent rendben találtam.

**Comment by noramurakozy** [comment]
A merge után nem futottak le helyesen a példakódok, hibás megvalósítást találtam a 4ad1ec0406c64ca3d23c340759c05367cf103af3 commit után. A result változónak rossz érték lett átadva, nem az if ágban lévőt, hanem a felette lévőt kell értékül adni az új függvényben, mivel false esetén - ami eddig a default paraméter volt, és cseréltük le - is az lenne az értéke.

**Comment by noramurakozy** [comment]
A hibát sikerült kijavítani, az issuet lezárom.

**Comment by micskeiz** [comment]
OK, csak így tovább a többi feladattal is.
