### ISSUE TITLE
Unit Tesztek készítése

### ISSUE THREAD

**Issue by noramurakozy** [BME-MIT-IET/IETeam-iet-2019#9]
A projekthez írni kell minél minőségibb, minél több, értelmes tesztet, ami a projekt minél nagyobb részét lefedi.
Az issue lezárását követően szükséges az ehhez tartozó wikioldal megírása is.

**Comment by noramurakozy** [comment]
A teszteket xUnit segítségével készítjük és futtatjuk.

**Comment by noramurakozy** [comment]
A tesztelés egyszerűsítése érdekében létrehoztunk egy GraphBuilder osztályt, amin, ha szükséges végezhetjük a teszteket.

A Model tesztek megírása után a kódlefedettség a következőképpen néz ki:

![image](https://user-images.githubusercontent.com/26260669/57619460-48441680-7586-11e9-8bce-3d32dd6080f9.png)

Látszik, hogy kb 23%-ban le van fedve a library Model szekciójának kódja, ezért úgy döntöttünk továbbhaladunk a másik két szekcióra.

### Commitok
32454ece30455e1315836548ec19c2584b4f3408
39ae3f34350a94fd8155236d9ef947844379e0c4

**Comment by noramurakozy** [comment]
A Query tesztek vegyesen tartalmaznak Query eredményre vonatkozó teszteket is, valamint a különböző query módosító osztályok tesztelését is, pl Filterek, Modifier-ek hozzáadásának tesztelését a Query-khez.
Összesen kb 30 Query teszt készült.

A Query tesztek megírása után a kódlefedettség:
![image](https://user-images.githubusercontent.com/26260669/57972670-ea586a00-799d-11e9-889f-52c4119d46c3.png)

Ezután lépünk tovább a Store tesztek írására, aminél szintén legalább 20%-os lefedettséget szeretnénk.

**Comment by miku00** [comment]
A Store tesztek a Store-ok létrehozásának és az ezekben tárolt elemek módositásának eseteihez kapcsolódnak.
A tesztek elkészítése során a StoreBuilder osztály létrehozása szükségesnek tűnt a tesztek kódjának rövidítése és átláthatósága érdekében. Ebben egy RDFMemoryStore-eal és egy RDFFederation-nel visszatérő függvény található.

A lefedettség a tesztek elkészítése után a következőképp néz ki:
![image](https://user-images.githubusercontent.com/37247013/57982928-074b7680-7a4c-11e9-9285-151e3e32cacf.png)

**Comment by balint245** [comment]
A Model tesztek a model-ben lévő Literal, Resource, graph típusú objektumokon végzett műveleteihez kapcsolódnak. ( létrehozás, törlés, tömbbe, gráfba illesztés...)

Kódlefedettség:
![image](https://user-images.githubusercontent.com/37247013/57982928-074b7680-7a4c-11e9-9285-151e3e32cacf.png)

**Comment by micskeiz** [comment]
@balint245 Ránéztem a munkádra, végül is rendben van. Máskor azonban figyelj arra, hogy hibás kódot ne kommitálj, rendezettebb legyen a commit history-d és a tesztjeidnél egyértelműbb legyen, hogy mik a tesztek célja.
